### ISSUE TITLE
drone list at most 100 repos from gitee.com

### ISSUE THREAD

**Issue by LinDong123a** [harness/drone#3217]
# Expected Behavior
After finishing configure gitee's OAuth2 for drone, drone server syncs all repos from gitee.com.
# Current Behavior
After finishing configure gitee's OAuth2 for drone, drone server only syncs at most 100 repos.
# Context
drone version: v1.12.1
# detail description
After checking source code from drone/service/repo/repo.go +52:
```go
        repos := []*core.Repository{}
	opts := scm.ListOptions{Size: 100}
	for {
		result, meta, err := s.client.Repositories.List(ctx, opts)
		if err != nil {
			return nil, err
		}
		for _, src := range result {
			if src != nil {
				repos = append(repos, convertRepository(src, s.visibility, s.trusted))
			}
		}
		opts.Page = meta.Page.Next
		opts.URL = meta.Page.NextURL

		if opts.Page == 0 && opts.URL == "" {
			break
		}
	}
```
I find that drone actually tries to sync all repos even if there is pagination in repo api. So I check the implementation from go-scm:v1.21.1, which is the dependant version for drone, and found an error in the source from go-scm/scm/drivce/gitee/gitee.go +128:
```go
func populatePageValues(req *scm.Request, resp *scm.Response) {
	last, totalError := strconv.Atoi(resp.Header.Get("total_page"))
	reqURL, err := url.Parse(req.Path)
	if err != nil {
		return
	}
	current, currentError := strconv.Atoi(reqURL.Query().Get("page"))
	if totalError != nil && currentError != nil {
		return
	}
	resp.Page.First = 1
	if last != 0 {
		resp.Page.Last = last
	}
	if current != 0 {
		if current < resp.Page.Last {
			resp.Page.Next = current + 1
		} else {
			resp.Page.Next = resp.Page.Last
		}
		if current > resp.Page.First {
			resp.Page.Prev = current - 1
		} else {
			resp.Page.Prev = resp.Page.First
		}
	}
}
```
The Page.Next will  be 2 when total_page > 1 and not page option is given as drone implement, which results in only 100 repos are accessed for gitee.com
# Possible Solution
After upgrading go-scm from v.1.21.1 to v.1.23.0, the problem could be solved.

**Comment by wmvm0** [comment]
跟我提的bug一样 https://github.com/drone/go-scm/issues/187

**Comment by LinDong123a** [comment]
go-scm v1.23.0 have solved the problem, so I think it is drone which should upgrade the go-scm  version

**Comment by kit101** [comment]
hi, @wmvm0 @LinDong123a 

The latest version already bump `go-scm` to v1.24.0.   [changelog](https://github.com/harness/drone/blob/v2.12.1/CHANGELOG.md)
