### ISSUE TITLE
Cron expression error 

### ISSUE THREAD

**Issue by gelleson** [harness/drone#3222]
I have tried to set up cron via drone CLI  weekly with custom time.
But I faced with a problem. When I used same pattern for weekly cron which I used for daily cron. I faced with an error 
For daily : 12 14 * * * * is ok 
For Weekly 12 14 * * 7  I see an error. 
```json
{"message":"Invalid Cronjob Expression"}
```
**Expected**
Should be same pattern to each cron or fill additional info in docs

**Comment by bradrydzewski** [comment]
This is expected because the cron library we use requires you to specify seconds:

> The cron expression represents a set of times, using 6 space-separated fields, including seconds.

You can learn more and see some examples in the docs:
<https://docs.drone.io/cron/#expressions>

**Comment by gelleson** [comment]
@bradrydzewski I have tried to run ``` bash drone cron add gelleson/drone-repo "weekly"  "0 14 14 * * 7" --branch main
client error 400: {"message":"Invalid Cronjob Expression"}``` inspired by docs. But I still see an error

**Comment by gelleson** [comment]
What was wrong?

**Comment by gelleson** [comment]
I found :) Sorry  :)
