### ISSUE TITLE
drone ci  manager: request queue item  manager: context canceled

### ISSUE THREAD

**Issue by wanghao123123** [harness/drone#3238]
![image](https://user-images.githubusercontent.com/38528031/177951985-59531c94-a9a8-41fd-9936-5c06a9a6545e.png)
![image](https://user-images.githubusercontent.com/38528031/177952029-82c3c23b-3f47-4af0-bf56-2f664802c60b.png)

No other error logs are seen

**Comment by wanghao123123** [comment]
drone.yml
![image](https://user-images.githubusercontent.com/38528031/177952271-133226de-c4ee-4c31-8acd-9c2aa1a740aa.png)

**Comment by kit101** [comment]
你启动drone-runner了吗？

**Comment by wanghao123123** [comment]
> 你启动drone-runner了吗？

启动了
![image](https://user-images.githubusercontent.com/38528031/177955427-42aa4a6e-2b33-480f-bc15-bd8c0afa5ffe.png)
![image](https://user-images.githubusercontent.com/38528031/177955517-9cf11600-87dd-46df-94cf-9b880dd5432a.png)

**Comment by kit101** [comment]
你看一下是不是因为你的`drone.yml`中指定了`kind: docker`，而`runner`的kind是`kubernetes`
