### ISSUE TITLE
downstream plugin step client error 404

### ISSUE THREAD

**Issue by vjvel** [harness/drone#3244]
Hi All,

we were using this step to trigger other project.

I have used admin token as secret 

- name: run-automation-framework
    image: plugins/downstream
    type: plugin
    settings:
      server: http://droneci.dev.demo.com
      token:
        from_secret: DOWNSTREAM_TOKEN
      fork: true
      repositories:
        - demo/demo-project@demo_master
    when:
      branch:
        - testpipeline

Getting the below error and we are using dockerized drone-server version 2.12   

```
latest: Pulling from plugins/downstream
Digest: sha256:b7924a1048636fbcf7ce9f0e706017c9b5ed705aa440ee8a76b387575f8b33e8
Status: Image is up to date for plugins/downstream:latest
time="2022-07-29T15:55:50Z" level=error msg="execution failed: unable to get latest build for demo/demoproject@demo_master: client error 404: {\"message\":\"sql: no rows in result set\"}\n"
```

@bradrydzewski please advise.

**Comment by bradrydzewski** [comment]
:wave: hey therre, for end-user support please use one of our community support channels, such as our [slack channel](https://join.slack.com/t/harnesscommunity/shared_invite/zt-y4hdqh7p-RVuEQyIl5Hcx4Ck8VCvzBw) or our [mailing list](https://community.harness.io/).
