### ISSUE TITLE
proposal: starlark: pass environment variables to context

### ISSUE THREAD

**Issue by condemil** [harness/drone#3252]
When custom build is created with custom parameters, these parameters will be available as environment variables. For now there is no way to access those key-value parameters from starlark. As a solution environment variables can be passed as a part of the ctx struct.

**Comment by bradrydzewski** [comment]
I believe the build parameters are passed here and accessible via `ctx.build.params`:
https://github.com/harness/drone/blob/master/plugin/converter/starlark/args.go#L145

**Comment by condemil** [comment]
I just tested and yes, when UI calls /builds endpoint the `content-length` is 0, so no parameters is passed from UI. I believe that is the reason why params is empty. I will close current issue as it appears the actual issue is with UI.
