### ISSUE TITLE
java client for drone api

### ISSUE THREAD

**Issue by yahaha-yes** [harness/drone#3253]
I implemented a simple java client for Drone Server Api, anyone in need can use it at will. :grinning: 
https://github.com/yahaha-yes/drone-api-java.git

**Comment by ShruthiHubb** [comment]
Thanks for sharing them! :)

**Comment by bradrydzewski** [comment]
@yahaha-yes thanks, added a reference to our docs
https://github.com/drone/docs/blob/master/content/api/overview.md
