### ISSUE TITLE
Add Version Info to API (and later CLI)

### ISSUE THREAD

**Issue by CMiksche** [harness/drone#3303]
I currently automate the updating of all my applications. Nearly every software I know has some way of outputting version information via either CLI or API.

Drone currently has no way of getting the version information via API or CLI. This feature should be added as it helps many people. Devs like me could automate updating Drone based on a check if the installed version is the current version and users who have issues could output version information in their Bug reports.

This should be added to the API and later to the CLI which uses the API.

**Comment by bradrydzewski** [comment]
You can use the `/version` endpoint to get the server version. Example https://cloud.drone.io/version

**Comment by CMiksche** [comment]
> You can use the `/version` endpoint to get the server version. Example https://cloud.drone.io/version

Ah thank you, I wasn't aware of this.

I am closing the Issue then.
