### ISSUE TITLE
ReferenceError: useLocation is not defined  

### ISSUE THREAD

**Issue by anerg2046** [harness/drone#3314]
Can not view EXECUTIONS detail

docker image sha256:6b0171d2d27aa1046927acc53f44cd264b94441d5c20ba6818bee2d0d37d4f0a

**Comment by quotengrote** [comment]
Same here:

Drone-Server: Tag=latest

Error:

![image](https://user-images.githubusercontent.com/38253905/233335756-65a66824-9a71-4685-8a4e-857f62f1a2c1.png)
![image](https://user-images.githubusercontent.com/38253905/233335807-df32c43d-df01-42f8-bd88-e8c34a033397.png)

**Comment by anerg2046** [comment]
> Same here:
> 
> Drone-Server: Tag=latest
> 
> Error:
> 
> ![image](https://user-images.githubusercontent.com/38253905/233335756-65a66824-9a71-4685-8a4e-857f62f1a2c1.png) ![image](https://user-images.githubusercontent.com/38253905/233335807-df32c43d-df01-42f8-bd88-e8c34a033397.png)
> 
> No problems with Tag=2

That's true. I've rollback to tag=2

**Comment by d1wilko** [comment]
Apologies about this folks - latest tag should now be fixed :)
