### ISSUE TITLE
Sub repository processing Not Found

### ISSUE THREAD

**Issue by dierbei** [harness/drone#3321]
Sub repository processing not supported at this time?

example: https://gitlab.com/paas/item/item-search-microservice.git

This can't be dealt with, can it solve the problem？

**Comment by bradrydzewski** [comment]
moving to https://github.com/harness/drone/issues/2009

**Comment by dierbei** [comment]
When I try to build a gitlab project, for example: [https://gitlab.com/paas/item/item-search-microservice.git；](https://gitlab.com/paas/item/item-search-microservice.git%EF%BC%9BGot) Got Not Found;

I try to modify the drone source code. For example: sync code warehouse, create, list, query；404 appears in the route；

I tried to URL-encode the parameters of the build to prevent the route from being found；
And decode after receiving the parameters；

Finally, I was surprised to find that it can be built normally;

```go
var (
	namespace = chi.URLParam(r, "owner")
	name      = chi.URLParam(r, "name")
)
decoded, err := url.QueryUnescape(namespace)
if err != nil {
	fmt.Println("decode error:", err)
}
namespace = decoded
```

**Comment by dierbei** [comment]
@bradrydzewski

**Comment by mailbyms** [comment]
> @bradrydzewski

They officially say they won't support subgroups, so I suggest switching to gitlab pipeline

**Comment by dierbei** [comment]
> > @bradrydzewski
> 
> They officially say they won't support subgroups, so I suggest switching to gitlab pipeline

That for our company's special business, I can only make source code changes, applicable to our company's own use;

**Comment by qianbeibuzui** [comment]
Is it finally time to support subgroups? Unfortunately, I have migrated to gitlab runner...
