### ISSUE TITLE
Filter builds by branch name

### ISSUE THREAD

**Issue by dcdourado** [harness/drone#3323]
The feature will allow us visualize build timeline for a specific branch more easily. Other CI tools like CircleCI have this and it is good for usability.

I imagine it something like this.

No filter selected:
![No filter selected](https://github.com/harness/drone/assets/41040569/6c6d0d85-991a-49db-86d9-f0230c4ef270)

Filter selected for branch "master":
![Filter selected](https://github.com/harness/drone/assets/41040569/24f85bde-48af-4f6d-a6f0-c7788185563f)

**Comment by bradrydzewski** [comment]
FYI looks like you are using Drone `0.8` which was EOL in 2019. The latest version of Drone is `2.17`.  There is currently no branch filter in newer versions of Drone, however, there is a branches page (below).

<img width="1328" alt="Screen Shot 2023-06-20 at 9 24 55 AM" src="https://github.com/harness/drone/assets/817538/e8814d5d-9041-4558-8f2a-c641d3402b71">

**Comment by dcdourado** [comment]
That would resolve the problem! Thanks for pointing it out @bradrydzewski
